import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";

const appProviders = readFileSync(new URL("../src/components/layout/app-providers.tsx", import.meta.url), "utf8");
const hydrator = readFileSync(new URL("../src/components/workspace/workspace-bootstrap-hydrator.tsx", import.meta.url), "utf8");
const workspaceApi = readFileSync(new URL("../src/services/api/workspace.ts", import.meta.url), "utf8");
const router = readFileSync(new URL("../src/router.tsx", import.meta.url), "utf8");
const userSession = readFileSync(new URL("../src/lib/user-session.ts", import.meta.url), "utf8");
const creationAgent = readFileSync(new URL("../src/pages/create/creation-agent-entry.tsx", import.meta.url), "utf8");
const sidebarNav = readFileSync(new URL("../src/components/layout/workspace-sidebar-nav.tsx", import.meta.url), "utf8");
const imageStorage = readFileSync(new URL("../src/services/image-storage.ts", import.meta.url), "utf8");
const fileStorage = readFileSync(new URL("../src/services/file-storage.ts", import.meta.url), "utf8");
const appTopNav = readFileSync(new URL("../src/components/layout/app-top-nav.tsx", import.meta.url), "utf8");
const workspaceProductCss = readFileSync(new URL("../src/styles/workspace-product.css", import.meta.url), "utf8");

test("local workspace bootstrap is the product startup contract", () => {
    expect(appProviders).toContain("WorkspaceBootstrapHydrator");
    expect(appProviders).not.toContain("AuthSessionHydrator");
    expect(hydrator).toContain("getWorkspaceBootstrap");
    expect(hydrator).not.toContain("getAuthSession");
    expect(hydrator).toContain("createLocalWorkspacePayload");
    expect(hydrator).toContain("applySession: applyUserSession");
    expect(hydrator).toContain("restoreModelConfig: hydrateLocalModelConfig");
    expect(workspaceApi).toContain('"/workspace/bootstrap"');
    expect(router).not.toContain('path: "/login"');
    expect(router).not.toContain('path: "/register"');
    expect(router).not.toContain("AuthScene");
    expect(router).toContain('path: "/tasks"');
    expect(router).toContain('path: "/projects"');
    expect(router).toContain('path: "/project"');
    expect(router).toContain('path: "/project/:projectId"');
    expect(router).toContain('path: "/project/:projectId/*"');
    // 根路径就是创作台；项目库入口由侧边栏的「项目」承担。
    expect(router).toContain('{ path: "/", element: deferred(<CreatePage />) }');
    expect(sidebarNav).toContain('"/project"');
    expect(appTopNav).not.toContain("app-workspace-local-announcement");
    expect(appTopNav).not.toContain("BannerAnnouncementsSlider");
    expect(workspaceProductCss).not.toContain("app-workspace-local-announcement");
    expect(workspaceProductCss).not.toContain(".app-workspace-shell:has(.assets-library-page)");
    expect(userSession).not.toContain("logout");
    expect(userSession).toContain("setWorkspaceCapabilitySnapshot");
    expect(userSession).toContain("payload.contractVersion");
    expect(userSession).not.toContain("installRemoteUserDataAutoSync");
    expect(userSession).not.toContain("syncRemoteUserData");
    expect(userSession).not.toContain("getModelCatalogForSession");
    expect(creationAgent).toContain("const localMode");
    expect(creationAgent).toContain("!localMode && !hasRemoteUserDataSyncSession()");
    expect(creationAgent).not.toContain("登录或同步会话尚未就绪");
    expect(sidebarNav).toContain("footer: []");
    expect(sidebarNav).not.toContain('title: "退出登录"');
    expect(imageStorage).toContain("const localRuntime = isLocalRuntimeMode();");
    expect(imageStorage).toContain("The desktop Go resource service is local storage");
    expect(imageStorage).not.toContain("if (!localOnly) try");
    expect(fileStorage).toContain("const localRuntime = isLocalRuntimeMode();");
    expect(fileStorage).toContain("The native desktop Go resource service is the canonical local store");
    expect(fileStorage).not.toContain("if (!localOnly) try");
});
